$mod = SUPER
$terminal = kitty
$fileManager = thunar
$launcher = rofi -no-config -show drun -display-drun "Type here to search for apps" -theme ~/.config/rofi/launcher.rasi
$wallpaperChooser = sh -lc '$HOME/ctfbox-rice/scripts/choose-wallpaper.sh'

monitor=,preferred,auto,1
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

exec-once = waybar
exec-once = dunst
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = sh -lc '$HOME/ctfbox-rice/scripts/launch-swaybg.sh'
exec-once = wl-paste --watch cliphist store

input {
    kb_layout = us
    repeat_rate = 45
    repeat_delay = 220
    follow_mouse = 1
}

general {
    gaps_in = 5
    gaps_out = 14
    border_size = 2
    col.active_border = rgba(c7bbffff) rgba(70c6deff) 45deg
    col.inactive_border = rgba(2c3440cc)
    layout = dwindle
    resize_on_border = false
}

decoration {
    rounding = 18

    shadow {
        enabled = true
        range = 18
        render_power = 4
        color = rgba(00000066)
    }

    blur {
        enabled = true
        size = 4
        passes = 1
        vibrancy = 0.14
    }
}

animations {
    enabled = yes
}

dwindle {
    pseudotile = true
    preserve_split = true
}

cursor {
    no_hardware_cursors = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

bind = $mod, Return, exec, $terminal
bind = $mod, D, exec, $launcher
bind = $mod, E, exec, $fileManager
bind = $mod, W, exec, $wallpaperChooser
bind = $mod, Q, killactive,
bind = $mod SHIFT, E, exit,
bind = $mod, F, fullscreen,
bind = $mod, V, togglefloating,
bind = $mod, Print, exec, grim -g "$(slurp)" - | wl-copy

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
